treewide: Fix error cause a function declaration is deprecated Fixes warns on clang 15.0.0:
../drivers/char/diag/diagchar_core.c:3499:18: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_ws_init()
                 ^
                  void
../drivers/char/diag/diagchar_core.c:3525:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_ws_on_notify()
                      ^
                       void
../drivers/char/diag/diagchar_core.c:3668:21: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_ws_release()
                    ^
                     void
3 errors generated.

../drivers/char/diag/diag_mux.c:52:18: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int diag_mux_init()
                 ^
                  void
../drivers/char/diag/diag_mux.c:79:19: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_mux_exit()
                  ^
                   void
2 errors generated.
make[4]: *** [../scripts/Makefile.build:285: drivers/char/diag/diag_mux.o] Error 1
make[4]: *** Waiting for unfinished jobs....
  CC      drivers/cpuidle/cpuidle.o
  LD      drivers/cpufreq/built-in.o
  CC      drivers/crypto/msm/qcedev.o
../drivers/char/diag/diag_memorydevice.c:85:22: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_md_open_all()
                     ^
                      void
../drivers/char/diag/diag_memorydevice.c:101:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_md_close_all()
                      ^
                       void
2 errors generated.

../drivers/char/diag/diag_dci.c:372:29: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_dci_wakeup_clients()
                            ^
                             void
1 error generated.

../drivers/media/platform/msm/camera_v2/common/msm_camera_tz_util.c:77:51: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct qseecom_handle *msm_camera_tz_get_ta_handle()
                                                  ^
                                                   void
1 error generated.

../drivers/media/platform/msm/vidc/msm_vidc_common.c:2635:35: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void msm_comm_handle_thermal_event()
                                  ^
                                   void
1 error generated.

../drivers/soc/qcom/msm_bus/msm_bus_rpm_smd.c:22:29: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void msm_bus_rpm_set_mt_mask()
                            ^
                             void
1 error generated.

../drivers/thermal/msm_thermal-dev.c:349:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int msm_thermal_ioctl_init()
                          ^
                           void
../drivers/thermal/msm_thermal-dev.c:412:31: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void msm_thermal_ioctl_cleanup()
                              ^
                               void
2 errors generated.

../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_main.c:7141:43: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
hdd_adapter_t *hdd_get_first_valid_adapter()
                                          ^
                                           void
1 error generated.

../drivers/soc/qcom/qdsp6v2/voice_svc.c:600:31: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static int voice_svc_dummy_reg()
                              ^
                               void
1 error generated.

../drivers/video/fbdev/msm/mdss_mdp.c:4857:32: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct irq_info *mdss_intr_line()
                               ^
                                void
1 error generated.

../drivers/video/fbdev/msm/mdss_util.c:235:42: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct mdss_util_intf *mdss_get_util_intf()
                                         ^
                                          void
1 error generated.

Signed-off-by: onettboots <blackcocopet@gmail.com>